export REDIS_HOST='127.0.0.1'
export REDIS_PORT='6379'
export REDIS_PSWD=''

export BITTREX_API_DOMAIN='https://bittrex.com/api/v1.1'
export BITTREX_API_KEY='xx'
export BITTREX_API_SEC='xx'

export HITBTC_API_DOMAIN='https://api.hitbtc.com'
export HITBTC_API_KEY='xx'
export HITBTC_API_SEC='xx'
export HITBTC_API_KEY_Y='xxx'
export HITBTC_API_SEC_Y='xxx'
export HITBTC_API_KEY_C='xxx'
export HITBTC_API_SEC_C='xxx'

export LIQUI_API_DOMAIN='https://api.liqui.io/tapi'
export LIQUI_API_KEY='xx'
export LIQUI_API_SEC='xx'

export BFX_API_DOMAIN='https://api.bitfinex.com/v1'
export BFX_API_KEY='xx'
export BFX_API_SEC='xx'

export BINANCE_API_DOMAIN='https://www.binance.com/api/v3'
export BINANCE_API_DOMAIN_V3='https://api.binance.com'
export BINANCE_API_KEY='xx'
export BINANCE_API_SEC='xx'
export BINANCE_API_KEY_WITHDRAW='yy'
export BINANCE_API_SEC_WITHDRAW='yy'

export HUOBI_API_DOMAIN_TRADE='https://api.huobi.pro'
export HUOBI_API_DOMAIN_MARKET='https://api.huobi.pro'
export HUOBI_API_KEY='1'
export HUOBI_API_SEC='2'

export URANUS_REPORT_RECIPIENT='nobody@gmail.com'

export URANUS_BASE_BTC='1'
export URANUS_BASE_DNT='2'

export BITTREX_API_DOMAIN=''
export BITTREX_API_KEY=''
export BITTREX_API_SEC=''
export BINANCE_API_DOMAIN=''
export BINANCE_API_DOMAIN_V3=''
export BINANCE_API_KEY_WITHDRAW=''
export BINANCE_API_SEC_WITHDRAW=''
export OKEX_API_SEC=''
export OKEX_API_KEY=''
export OKEX_TRADE_PSWD=''
export OKEX_API_V3_SEC=''
export OKEX_API_V3_KEY=''
export OKEX_API_V3_PSWD=''
export HUOBI_API_SEC=''
export HUOBI_API_KEY=''
export HUOBI_API_PRIVATE_KEY=''
export HUOBI_A_API_SEC=''
export HUOBI_A_API_KEY=''
export HUOBI_A_API_PRIVATE_KEY=''
export HUOBI_B_API_SEC=''
export HUOBI_B_API_KEY=''
export HUOBI_B_API_PRIVATE_KEY=''
export HITBTC_API_DOMAIN=''
export HITBTC_API_KEY=''
export HITBTC_API_SEC=''
export POLO_API_SEC=''
export POLO_API_KEY=''
export ZB_TRADE_PSWD=''
export ZB_API_SEC=''
export ZB_API_KEY=''
export BITMEX_API_DOMAIN=''
export BITMEX_API_KEY=''
export BITMEX_API_SEC=''
export KRAKEN_API_KEY=''
export KRAKEN_API_SEC=''
export BITSTAMP_API_KEY=''
export BITSTAMP_API_SEC=''
